// ⚠ VENDORED — DO NOT EDIT THIS FILE.
// Source of truth: plugins/workflow/hooks/guards/dispatch-first-core.ts
// Regenerate: node scripts/vendor-guards.mjs   (CI/pre-commit gate: --check)

/**
 * Shared decision logic for the dispatch-first coordinator guard.
 *
 * This module is PURE LOGIC. It performs NO process.exit, NO stdin read, and
 * has NO `main()` / self-execution at import time. The Claude Code hook
 * (`dispatch-first.ts`) imports from here; the Codex/OpenCode adapters (plan
 * item 2.2) import their vendored copy. Each owns its own I/O surface.
 *
 * What it enforces — the workflow contract's "Dispatch-first gate"
 * (skills/shared/workflow-contract.md): a cheap coordinator (Sonnet, Terra)
 * must dispatch the retained frontier owner BEFORE it reads implementation
 * source, inspects deployments or logs, or runs diagnostics. The contract was
 * prose and was being violated ~6:1 (a traced argus coordinator ran 59 tool
 * calls over 13 minutes before its first `Agent` dispatch). This is the
 * structural version: count the investigation tool calls in the current turn
 * that precede any dispatch, and warn, then block, past a threshold.
 *
 * Scope decisions, in priority order:
 *   1. Builders are NEVER touched. Any model outside COORDINATOR_MODEL_PATTERNS
 *      (Fable, Opus, Astra, Sol, Haiku, unknown) → no-op.
 *   2. Subagents are never touched (an Explore or fork subagent is SUPPOSED to
 *      grep and read). The adapter passes `inSubagent` from the hook input's
 *      `agent_id`, which is only present inside a subagent (hooks doc,
 *      "Common input fields").
 *   3. A turn is "since the most recent real user message". Tool results also
 *      arrive as `type: "user"` transcript lines, so a user line whose content
 *      carries a `tool_result` block is NOT a boundary.
 *   4. Any dispatch (DISPATCH_TOOLS) after that boundary → no-op for the rest
 *      of the turn. `SendMessage` counts: continuing a retained worker is the
 *      contract's sanctioned follow-up shape, and a coordinator that has just
 *      briefed its worker and then reads run.md is not pre-solving.
 *   5. Purely logistical calls (LOGISTICAL_BASH_PATTERNS, INSTRUCTION_FILE_PATTERNS)
 *      are neither counted nor gated.
 *
 * Failure posture: this is a DISCIPLINE guard, not a safety boundary. An
 * unreadable transcript, a malformed payload or an undeterminable model resolve
 * to `allow` (with a `skipped` reason the adapter logs). The asymmetry is
 * deliberate — blocking a frontier builder because a transcript could not be
 * parsed costs far more than missing one nudge. Do not "harden" this to fail
 * closed without re-reading item 1 above.
 */
import { readFileSync } from 'fs';

// ── Roster and allowlists — the single place to change them ──────────────────

/** Models that act as coordinators under the orchestrate workflow. */
export const COORDINATOR_MODEL_PATTERNS: RegExp[] = [
    /^claude-sonnet-/,
    /^gpt-5\.6-terra/,
];

/** PreToolUse tool names that count as pre-dispatch investigation. */
export const INVESTIGATION_TOOLS: ReadonlySet<string> = new Set([
    'Bash',
    'Read',
    'Grep',
    'Glob',
    'WebFetch',
]);

/** Tool names whose use in the turn means the coordinator has dispatched. */
export const DISPATCH_TOOLS: ReadonlySet<string> = new Set(['Agent', 'Task', 'SendMessage']);

/**
 * Bash commands the coordinator may run without dispatching. Applied per
 * pipeline/list segment: every segment of a compound command must match.
 */
export const LOGISTICAL_BASH_PATTERNS: RegExp[] = [
    /^\s*gh pr view\b/,
    /^\s*gh api\b/,
    /^\s*mkdir\b/,
    /^\s*git fetch\b/,
    /^\s*ls\b/,
    /^\s*pwd\b/,
    /^\s*date\b/,
    /^\s*echo\b/,
];

/** Files the coordinator may Read: its own instructions and the run record. */
export const INSTRUCTION_FILE_PATTERNS: RegExp[] = [
    /(^|\/)plan\.md$/,
    /(^|\/)run\.md$/,
    /(^|\/)CLAUDE\.md$/,
    /(^|\/)SKILL\.md$/,
];

/** Warn on the call AFTER this many counted calls (4th at 3). */
export const DEFAULT_WARN_THRESHOLD = 3;
/** Block on the call AFTER this many counted calls (9th at 8). */
export const DEFAULT_BLOCK_THRESHOLD = 8;

export const ENV_DISABLE = 'BOOTSTRAP_DISPATCH_FIRST';
export const ENV_WARN = 'BOOTSTRAP_DISPATCH_FIRST_WARN';
export const ENV_BLOCK = 'BOOTSTRAP_DISPATCH_FIRST_BLOCK';

// ── Types ────────────────────────────────────────────────────────────────────

export interface DispatchFirstThresholds {
    warn: number;
    block: number;
    disabled: boolean;
    /** Env values that were present but unusable; the default was kept. */
    ignoredEnv: string[];
}

export interface CountedCall {
    tool: string;
    summary: string;
}

export interface TurnAnalysis {
    /** Model of the most recent assistant message, or null if none found. */
    model: string | null;
    /** Investigation calls since the last real user message, excluding `currentToolUseId`. */
    investigationCalls: CountedCall[];
    /** True when any DISPATCH_TOOLS tool_use appears since the last real user message. */
    dispatched: boolean;
    /** True when the transcript held at least one parseable line. */
    parsed: boolean;
}

export interface DispatchFirstInput {
    /** Raw transcript JSONL text, or null when it could not be read. */
    transcriptText: string | null;
    toolName: string;
    toolInput: Record<string, unknown>;
    /** `tool_use_id` from the hook payload; excluded from the prior-call count. */
    toolUseId?: string;
    /** True when the hook fired inside a subagent (`agent_id` present). */
    inSubagent?: boolean;
    env: Record<string, string | undefined>;
}

export interface DispatchFirstVerdict {
    action: 'allow' | 'warn' | 'block';
    /** Message for the model (warn: additionalContext; block: stderr). */
    reason?: string;
    /** Ordinal of the current call among counted calls this turn (0 when not counted). */
    count: number;
    model: string | null;
    calls: CountedCall[];
    /** Why the guard stood down, when it did. */
    skipped?: string;
    thresholds: DispatchFirstThresholds;
}

// ── Predicates ───────────────────────────────────────────────────────────────

export function isCoordinatorModel(model: string | null | undefined): boolean {
    if (typeof model !== 'string' || !model) return false;
    return COORDINATOR_MODEL_PATTERNS.some((rx) => rx.test(model));
}

/**
 * Split a shell command into its list/pipeline segments. Deliberately coarse:
 * the allowlist is a courtesy for logistics, not a security boundary, and the
 * default mode is warn. A compound whose every segment is logistical passes.
 */
export function splitCommandSegments(command: string): string[] {
    return command
        .split(/\n|&&|\|\||;|\|/)
        .map((s) => s.trim())
        .filter((s) => s.length > 0);
}

export function isLogisticalBash(command: string): boolean {
    const segments = splitCommandSegments(command);
    if (segments.length === 0) return true;
    return segments.every((seg) => LOGISTICAL_BASH_PATTERNS.some((rx) => rx.test(seg)));
}

export function isInstructionFile(filePath: string): boolean {
    return INSTRUCTION_FILE_PATTERNS.some((rx) => rx.test(filePath));
}

/** True when the call is allowlisted logistics and must not be counted or gated. */
export function isLogisticalToolUse(toolName: string, toolInput: Record<string, unknown>): boolean {
    if (toolName === 'Bash') {
        const command = typeof toolInput.command === 'string' ? toolInput.command : '';
        return isLogisticalBash(command);
    }
    if (toolName === 'Read') {
        const filePath = typeof toolInput.file_path === 'string' ? toolInput.file_path : '';
        return isInstructionFile(filePath);
    }
    return false;
}

/** One-line description of a counted call for the diagnostic log. */
export function summarizeToolUse(toolName: string, toolInput: Record<string, unknown>): string {
    const pick = (key: string): string | null =>
        typeof toolInput[key] === 'string' ? (toolInput[key] as string) : null;
    const raw = pick('command') ?? pick('file_path') ?? pick('pattern') ?? pick('url') ?? '';
    const oneLine = raw.replace(/\s+/g, ' ').trim();
    return oneLine.length > 80 ? `${oneLine.slice(0, 77)}...` : oneLine;
}

// ── Transcript analysis ──────────────────────────────────────────────────────

interface TranscriptLine {
    type?: string;
    isSidechain?: boolean;
    message?: {
        role?: string;
        model?: string;
        content?: unknown;
    };
}

interface ContentBlock {
    type?: string;
    id?: string;
    name?: string;
    input?: unknown;
}

export function parseTranscript(text: string): TranscriptLine[] {
    const lines: TranscriptLine[] = [];
    for (const line of text.split('\n')) {
        if (!line.trim()) continue;
        try {
            const parsed = JSON.parse(line);
            if (parsed && typeof parsed === 'object') lines.push(parsed as TranscriptLine);
        } catch {
            // A torn tail line (the transcript is appended live) is expected; skip it.
        }
    }
    return lines;
}

function contentBlocks(line: TranscriptLine): ContentBlock[] {
    const content = line.message?.content;
    return Array.isArray(content) ? (content as ContentBlock[]) : [];
}

/**
 * A real user turn: `type: "user"` whose content is a string, or a block array
 * with no `tool_result` block. Tool results are delivered as user-role lines
 * too, and they must not reset the count.
 */
export function isUserTurnBoundary(line: TranscriptLine): boolean {
    if (line.type !== 'user') return false;
    const content = line.message?.content;
    if (typeof content === 'string') return true;
    if (!Array.isArray(content)) return false;
    return !(content as ContentBlock[]).some((b) => b?.type === 'tool_result');
}

export function analyzeTurn(lines: TranscriptLine[], currentToolUseId?: string): TurnAnalysis {
    const main = lines.filter((l) => l.isSidechain !== true);
    let model: string | null = null;
    const investigationCalls: CountedCall[] = [];
    let dispatched = false;

    for (let i = main.length - 1; i >= 0; i--) {
        const line = main[i];
        if (isUserTurnBoundary(line)) break;
        if (line.type !== 'assistant') continue;
        const m = line.message?.model;
        if (model === null && typeof m === 'string' && m && !m.startsWith('<')) model = m;
        for (const block of contentBlocks(line)) {
            if (block?.type !== 'tool_use' || typeof block.name !== 'string') continue;
            if (DISPATCH_TOOLS.has(block.name)) dispatched = true;
            if (!INVESTIGATION_TOOLS.has(block.name)) continue;
            if (currentToolUseId && block.id === currentToolUseId) continue;
            const input = (block.input && typeof block.input === 'object')
                ? (block.input as Record<string, unknown>)
                : {};
            if (isLogisticalToolUse(block.name, input)) continue;
            investigationCalls.unshift({ tool: block.name, summary: summarizeToolUse(block.name, input) });
        }
    }

    // First call of a turn has no assistant line in the window yet (or the
    // window's assistant lines may be tool-only): fall back to the most recent
    // assistant model anywhere. A `/model` switch mid-session is honoured
    // because we read the LATEST assistant line, not the first.
    if (model === null) {
        for (let i = main.length - 1; i >= 0; i--) {
            const m = main[i].message?.model;
            if (main[i].type === 'assistant' && typeof m === 'string' && m && !m.startsWith('<')) {
                model = m;
                break;
            }
        }
    }

    return { model, investigationCalls, dispatched, parsed: main.length > 0 };
}

// ── Thresholds ───────────────────────────────────────────────────────────────

export function resolveThresholds(env: Record<string, string | undefined>): DispatchFirstThresholds {
    const ignoredEnv: string[] = [];
    const readInt = (name: string, fallback: number): number => {
        const raw = env[name];
        if (raw === undefined || raw === '') return fallback;
        const n = Number.parseInt(raw, 10);
        if (!Number.isInteger(n) || n < 0 || String(n) !== raw.trim()) {
            ignoredEnv.push(`${name}=${JSON.stringify(raw)}`);
            return fallback;
        }
        return n;
    };
    const disabledRaw = (env[ENV_DISABLE] ?? '').trim().toLowerCase();
    const disabled = disabledRaw === 'off' || disabledRaw === '0' || disabledRaw === 'false';
    let warn = readInt(ENV_WARN, DEFAULT_WARN_THRESHOLD);
    let block = readInt(ENV_BLOCK, DEFAULT_BLOCK_THRESHOLD);
    if (block < warn) {
        // A block floor below the warn floor is a misconfiguration; keep the
        // pair coherent rather than blocking before warning.
        ignoredEnv.push(`${ENV_BLOCK}<${ENV_WARN} (block raised to warn)`);
        block = warn;
    }
    return { warn, block, disabled, ignoredEnv };
}

// ── Verdict ──────────────────────────────────────────────────────────────────

export function evaluateDispatchFirst(input: DispatchFirstInput): DispatchFirstVerdict {
    const thresholds = resolveThresholds(input.env);
    const base = { count: 0, model: null as string | null, calls: [] as CountedCall[], thresholds };

    if (thresholds.disabled) return { ...base, action: 'allow', skipped: `${ENV_DISABLE} is off` };
    if (input.inSubagent) return { ...base, action: 'allow', skipped: 'subagent context' };
    if (!INVESTIGATION_TOOLS.has(input.toolName)) {
        return { ...base, action: 'allow', skipped: `tool ${input.toolName} not counted` };
    }
    if (input.transcriptText === null) {
        return { ...base, action: 'allow', skipped: 'transcript unreadable' };
    }

    const turn = analyzeTurn(parseTranscript(input.transcriptText), input.toolUseId);
    const withModel = { ...base, model: turn.model, calls: turn.investigationCalls };

    if (!turn.parsed) return { ...withModel, action: 'allow', skipped: 'transcript empty' };
    if (turn.model === null) return { ...withModel, action: 'allow', skipped: 'model undeterminable' };
    if (!isCoordinatorModel(turn.model)) {
        return { ...withModel, action: 'allow', skipped: `builder model ${turn.model}` };
    }
    if (turn.dispatched) return { ...withModel, action: 'allow', skipped: 'dispatched this turn' };
    if (isLogisticalToolUse(input.toolName, input.toolInput)) {
        return { ...withModel, action: 'allow', skipped: 'logistical call' };
    }

    const calls = [
        ...turn.investigationCalls,
        { tool: input.toolName, summary: summarizeToolUse(input.toolName, input.toolInput) },
    ];
    const count = calls.length;
    const verdict = { ...withModel, calls, count };

    if (count > thresholds.block) {
        return {
            ...verdict,
            action: 'block',
            reason:
                `BLOCKED: dispatch-first — ${count} investigation calls this turn with no Agent dispatch ` +
                `(${turn.model}; limit ${thresholds.block}). The contract says the coordinator dispatches the ` +
                `retained frontier owner before investigating. Dispatch now with the Agent tool; do not keep ` +
                `reading, grepping or running diagnostics. Tune: ${ENV_WARN}/${ENV_BLOCK}; disable: ${ENV_DISABLE}=off.`,
        };
    }
    if (count > thresholds.warn) {
        return {
            ...verdict,
            action: 'warn',
            reason:
                `GATED: dispatch-first — ${count} investigation calls this turn with no Agent dispatch ` +
                `(${turn.model}). The contract says dispatch the frontier owner before investigating. ` +
                `Dispatch now, or record in run.md why this is purely logistical. ` +
                `This tool call was allowed; the guard blocks after ${thresholds.block}.`,
        };
    }
    return { ...verdict, action: 'allow' };
}

/** Read the transcript; null on any failure (the caller treats null as "stand down"). */
export function loadTranscript(transcriptPath: unknown): string | null {
    if (typeof transcriptPath !== 'string' || !transcriptPath) return null;
    try {
        return readFileSync(transcriptPath, 'utf-8');
    } catch {
        return null;
    }
}

/** Diagnostic line for stderr: action, model, count and every counted call. */
export function formatDecisionLog(verdict: DispatchFirstVerdict): string {
    const calls = verdict.calls.map((c) => `${c.tool}:${c.summary || '-'}`).join(' | ');
    const env = verdict.thresholds.ignoredEnv.length
        ? ` ignoredEnv=[${verdict.thresholds.ignoredEnv.join(', ')}]`
        : '';
    return `[dispatch-first] ${verdict.action} model=${verdict.model ?? '-'} count=${verdict.count} ` +
        `warn>${verdict.thresholds.warn} block>${verdict.thresholds.block}${env} calls: ${calls || '-'}`;
}
