// ⚠ VENDORED — DO NOT EDIT THIS FILE.
// Source of truth: plugins/workflow/hooks/guards/file-protection-core.ts
// Regenerate: node scripts/vendor-guards.mjs   (CI/pre-commit gate: --check)

/**
 * Shared decision logic for the file-protection guard. PURE: no I/O, no stdin,
 * no process.exit, no self-execution at import time.
 *
 * This is the SINGLE SOURCE OF TRUTH for "which edit targets are protected".
 * Each runtime ships a thin adapter that owns its own I/O surface and reuses
 * this core, so they can never drift:
 *   - Claude:   file-protection.ts          (Edit|MultiEdit|Write PreToolUse hook, exit 2)
 *   - OpenCode: opencode-guard.ts           (tool.execute.before on edit/write → throw)
 *   - Codex:    codex-hooks/runner.ts        (Edit/apply_patch PreToolUse → deny decision)
 *
 * Vendored into workflow-agents by scripts/vendor-guards.mjs (--check gated).
 */

// Explicitly allowed files (template files that look like protected ones).
// Checked BEFORE the protected patterns.
export const ALLOWED_FILES = [
    '.env.example',
    '.env.sample',
    '.env.template',
    '.gitignore',
    '.dockerignore',
];

// Protected path segments — block if the path contains any of these.
export const PROTECTED_SEGMENTS = [
    '.git/',
    '.git\\', // Windows-style
    'package-lock.json',
    'yarn.lock',
    'pnpm-lock.yaml',
    '.env',
    '.env.local',
    '.env.production',
    '.env.development',
];

// Protected glob patterns (IaC state/config).
export const PROTECTED_GLOBS = [/^infra\/terraform\//, /^terraform\//];

/** Edit-tool names across runtimes (Claude / OpenCode / Codex). */
export const EDIT_TOOLS = new Set([
    'Edit',
    'MultiEdit',
    'Write', // Claude
    'edit',
    'write',
    'write_file',
    'create_file', // OpenCode / generic
    'apply_patch', // Codex
]);

/** Returns true if an edit to `path` should be blocked. */
export function isProtectedEditPath(path: string): boolean {
    if (!path) return false;

    // Allowlist first (template files that look like protected files).
    for (const allowed of ALLOWED_FILES) {
        if (path.endsWith(allowed)) return false;
    }
    // Segment-contains.
    for (const segment of PROTECTED_SEGMENTS) {
        if (path.includes(segment)) return true;
    }
    // Glob patterns.
    for (const pattern of PROTECTED_GLOBS) {
        if (pattern.test(path)) return true;
    }
    return false;
}

/** Extract file paths from the codex `apply_patch` envelope format. */
export function filePathsFromPatch(text: unknown): string[] {
    if (typeof text !== 'string') return [];
    const paths: string[] = [];
    for (const line of text.split('\n')) {
        const m = line.match(/^\*\*\* (?:Add|Update|Delete) File: (.+)$/);
        if (m) paths.push(m[1].trim());
    }
    return paths;
}

/**
 * Pull every edit target from a tool_input across runtimes:
 *   - Claude:   { file_path } | { edits: [{ file_path }] }
 *   - OpenCode: { path } | { file_path }
 *   - Codex:    { patch | diff | input } (apply_patch envelope), { paths }, { files }
 */
export function editPathsFromToolInput(toolInput: Record<string, unknown> = {}): string[] {
    const paths: string[] = [];

    // file_path (Claude), path (generic), filePath (OpenCode edit/write tools).
    for (const key of ['file_path', 'path', 'filePath'] as const) {
        const v = toolInput[key];
        if (typeof v === 'string') paths.push(v);
    }
    for (const key of ['paths', 'files'] as const) {
        const v = toolInput[key];
        if (Array.isArray(v)) {
            for (const item of v) if (typeof item === 'string') paths.push(item);
        }
    }
    if (Array.isArray(toolInput.edits)) {
        for (const edit of toolInput.edits as Array<Record<string, unknown>>) {
            if (edit && typeof edit.file_path === 'string') paths.push(edit.file_path);
            if (edit && typeof edit.path === 'string') paths.push(edit.path);
        }
    }
    paths.push(...filePathsFromPatch(toolInput.patch ?? toolInput.diff ?? toolInput.input));

    return [...new Set(paths.filter(Boolean))];
}

/**
 * Evaluate an edit tool call. Returns the first protected path (the block
 * reason) or null when allowed. Callers own the block I/O.
 */
export function checkEditProtection(
    toolName: string,
    toolInput: Record<string, unknown> = {},
): string | null {
    if (!EDIT_TOOLS.has(toolName)) return null;
    for (const p of editPathsFromToolInput(toolInput)) {
        if (isProtectedEditPath(p)) return p;
    }
    return null;
}
