#!/usr/bin/env node
/**
 * Vendor the shared destructive-guard core into each runtime plugin.
 *
 * SINGLE SOURCE OF TRUTH:
 *   plugins/workflow/hooks/guards/block-destructive-core.ts
 * Vendored (generated, do-not-edit copies) into:
 *   plugins/workflow-agents/hooks/guards/
 *
 * Why vendor instead of cross-import: the core is runtime-neutral decision
 * logic (`evaluateBashCommand` + the destructive-command pattern table + the
 * NanoClaw session-DB approval gate). Each runtime ships a THIN adapter that
 * imports its own co-located copy. No plugin reaches across into another
 * plugin's tree — which would break under isolated host marketplace caches,
 * where (e.g.) codex's installed plugin cache does NOT contain the Claude
 * `workflow` plugin. Vendoring keeps every plugin self-contained.
 *
 * Drift is prevented by the `--check` gate (run in CI / pre-commit), the same
 * model as `plugins/workflow-agents/scripts/sync-codex-agents.mjs`.
 *
 * Usage:
 *   node scripts/vendor-guards.mjs           # write/refresh vendored copies
 *   node scripts/vendor-guards.mjs --check   # exit 1 if any copy is stale
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SOURCE_DIR = path.join(REPO, 'plugins/workflow/hooks/guards');

// Files vendored verbatim (with a banner) from SOURCE_DIR into each target dir.
const VENDORED_FILES = ['block-destructive-core.ts', 'file-protection-core.ts', 'email-gate-core.ts'];
const TARGET_DIRS = [path.join(REPO, 'plugins/workflow-agents/hooks/guards')];

function banner(srcRel) {
  return (
    `// ⚠ VENDORED — DO NOT EDIT THIS FILE.\n` +
    `// Source of truth: ${srcRel}\n` +
    `// Regenerate: node scripts/vendor-guards.mjs   (CI/pre-commit gate: --check)\n` +
    `\n`
  );
}

function rendered(file) {
  const src = fs.readFileSync(path.join(SOURCE_DIR, file), 'utf8');
  const srcRel = path.relative(REPO, path.join(SOURCE_DIR, file));
  return banner(srcRel) + src;
}

function main() {
  const check = process.argv.includes('--check');
  const stale = [];

  for (const dir of TARGET_DIRS) {
    for (const file of VENDORED_FILES) {
      const content = rendered(file);
      const target = path.join(dir, file);
      const current = fs.existsSync(target) ? fs.readFileSync(target, 'utf8') : null;
      if (current !== content) {
        stale.push(path.relative(REPO, target));
        if (!check) {
          fs.mkdirSync(dir, { recursive: true });
          fs.writeFileSync(target, content);
        }
      }
    }
  }

  if (check) {
    if (stale.length) {
      console.error(
        `vendor-guards: STALE vendored guard copies (run: node scripts/vendor-guards.mjs):\n  ${stale.join('\n  ')}`,
      );
      process.exit(1);
    }
    console.log('vendor-guards: all vendored guard copies up to date ✓');
    return;
  }

  console.log(
    stale.length
      ? `vendor-guards: refreshed ${stale.length} file(s):\n  ${stale.join('\n  ')}`
      : 'vendor-guards: already up to date ✓',
  );
}

main();
